### ISSUE TITLE
cant compile, too big

### ISSUE THREAD

**Issue by kaefert** [moononournation/Arduino_BLE_Scanner#2]
Hello!

I found your BLE Scanner + HTTP Post code through Google -> https://www.instructables.com/id/Nano-ESP32-BLE-Scanner/ and thought it would make a wonderful starting point for my application (since I want to receive data through BLE and forward it to HTTP).

Sadly my Arduino IDE says it's too big and it can't compile it for the ESP32 Chip:

```
Archiving built core (caching) in: /tmp/arduino_cache_662201/core/core_espressif_esp32_esp32_PSRAM_disabled,PartitionScheme_default,FlashMode_qio,FlashFreq_80,FlashSize_4M,UploadSpeed_921600,DebugLevel_none_4f585c99949505753064c478a7a2e8d4.a
Sketch uses 1592898 bytes (121%) of program storage space. Maximum is 1310720 bytes.
Global variables use 79136 bytes (24%) of dynamic memory, leaving 248544 bytes for local variables. Maximum is 327680 bytes.

Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board ESP32 Dev Module.
```

Can you help me please? Thank you!

**Comment by kaefert** [comment]
Ah okey, so I need to modify those two files:
* ~/Arduino/hardware/espressif/esp32/boards.txt
* ~/Arduino/hardware/espressif/esp32/tools/partitions/default.csv

as described in https://www.instructables.com/id/Nano-ESP32-BLE-Scanner/

I will try that now.

**Comment by kaefert** [comment]
Damn. It won't even fit with those modifications described on this instructable page.. please help:

```
Warning: Board espressif:esp32:Coreesp32 doesn't define a 'build.board' preference. Auto-set to: ESP32_COREESP32
Archiving built core (caching) in: /tmp/arduino_cache_655597/core/core_espressif_esp32_esp32_PSRAM_disabled,PartitionScheme_default,FlashMode_qio,FlashFreq_80,FlashSize_4M,UploadSpeed_921600,DebugLevel_none_4f585c99949505753064c478a7a2e8d4.a
Sketch uses 1592890 bytes (101%) of program storage space. Maximum is 1572864 bytes.

Global variables use 78920 bytes (24%) of dynamic memory, leaving 248760 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board ESP32 Dev Module.
```

**Comment by jonabert** [comment]
you probably forgot to set the right partition scheme (noOTA) in Arduino LE

**Comment by moononournation** [comment]
This problem can be in latest software by selecting Partition Scheme: No OTA (Large APP)
